[package]
name = "proto-game"
version = "0.1.0"
authors = ["Roel van Alst <roel.vanalst@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["wee_alloc"]

[dependencies]
wee_alloc = { version = "0.4.5", optional = true }
