[workspace]

members = [
    "art/core",
    "art/gui",
    "art/snes",
    "art/snes-cli",
    "geom",
    "cache",
    "prototype/proto-common",
    "prototype/proto-core",
    "prototype/proto-game",
    "proto/common",
    "proto/core",
    "proto/game",
    "proto/logger",
]
