[workspace]

members = [
    "art-extractor/core",
    "art-extractor/gui",
    "art-extractor/snes",
    "geom",
    "cache",
    "prototype/proto-common",
    "prototype/proto-core",
    "prototype/proto-game",
]
