[package]
name = "art-extractor-snes"
version = "0.1.0"
edition = "2021"

[dependencies]
art-extractor-core = { path = "../core" }
serde = { version = ">=1, <2", features = ["derive"] }
serde_json = ">=1, <2"
ves-geom = { path = "../../geom" }

[dev-dependencies]
bmp = ">= 0.4, <1"