[package]
name = "proto-core"
version = "0.1.0"
authors = ["knonderful <knonderful@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmtime = "0.23.0"
anyhow = "1.0.38"
parity-wasm = "0.42.1"
libretro-backend = "0.2.1"
