[package]
name = "ves-art-snes-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ves-art-snes = { path = "../snes" }
clap = { version = ">=3, <4", features = ["derive"] }
anyhow = ">=1, <2"
bincode = ">= 1.3, <2"
