[package]
name = "art-extractor-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rgb = ">=0.8, <1"
serde = { version = ">=1, <2", features = ["derive"] }
ves-geom = { path = "../../geom" }
ves-geom-artwork = { path = "../../geom-artwork" }
